// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using computrized_maintenance_Data_Access.Data;

#nullable disable

namespace computrized_maintenance_Data_Access.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260224145015_update_some_entity_propeties")]
    partial class update_some_entity_propeties
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("computrized_maintenance_Data_Access.Entites.AssetsManagment.Asset", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AssetCategoryID")
                        .HasColumnType("int");

                    b.Property<int>("AssetLocationID")
                        .HasColumnType("int");

                    b.Property<string>("AssetName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AssetStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssetTagNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateAssetDate")
                        .HasColumnType("datetime");

                    b.Property<int>("CreateByUser")
                        .HasColumnType("int");

                    b.Property<string>("Criticality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("InstallationDate")
                        .HasColumnType("datetime");

                    b.Property<string>("ManufactuerModelNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ManufactuerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MeterReading")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PurchaseCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("UpdateAssetDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("WarrantyExpiryDate")
                        .HasColumnType("date");

                    b.HasKey("ID")
                        .HasAnnotation("SqlServer = Identity", "(1,1)");

                    b.HasIndex("AssetCategoryID")
                        .IsUnique();

                    b.HasIndex("AssetLocationID")
                        .IsUnique();

                    b.ToTable("Assets", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AssetCategoryID = 1,
                            AssetLocationID = 2,
                            AssetName = "HVAC Unit - Floor 3",
                            AssetStatus = "Active",
                            AssetTagNumber = "HVAC-3F-01",
                            CreateAssetDate = new DateTime(2022, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateByUser = 1,
                            Criticality = "High",
                            InstallationDate = new DateTime(2022, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ManufactuerModelNumber = "24VNA9",
                            ManufactuerName = "Carrier",
                            MeterReading = "Hours",
                            PurchaseCost = 12500.00m,
                            PurchaseDate = new DateTime(2022, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WarrantyExpiryDate = new DateTime(2027, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 2,
                            AssetCategoryID = 2,
                            AssetLocationID = 1,
                            AssetName = "Forklift #5",
                            AssetStatus = "UnderMaintenance",
                            AssetTagNumber = "FL-005",
                            CreateAssetDate = new DateTime(2021, 8, 12, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            CreateByUser = 1,
                            Criticality = "Medium",
                            ManufactuerModelNumber = "8FGCU25",
                            ManufactuerName = "Toyota",
                            MeterReading = "Hours",
                            PurchaseCost = 32000.00m,
                            PurchaseDate = new DateTime(2021, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdateAssetDate = new DateTime(2023, 11, 15, 20, 12, 0, 0, DateTimeKind.Unspecified),
                            WarrantyExpiryDate = new DateTime(2024, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 3,
                            AssetCategoryID = 3,
                            AssetLocationID = 3,
                            AssetName = "Server Rack UPS",
                            AssetStatus = "Active",
                            AssetTagNumber = "IT-UPS-02",
                            CreateAssetDate = new DateTime(2023, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateByUser = 1,
                            Criticality = "High",
                            InstallationDate = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ManufactuerModelNumber = "SMX1500RM2U",
                            ManufactuerName = "APC",
                            MeterReading = "PowerCycles",
                            PurchaseCost = 2200.00m,
                            PurchaseDate = new DateTime(2023, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WarrantyExpiryDate = new DateTime(2026, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("computrized_maintenance_Data_Access.Entites.AssetsManagment.AssetImage", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AssetID")
                        .HasColumnType("int");

                    b.Property<short>("ImageHeight")
                        .HasColumnType("smallint");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("ImageWidth")
                        .HasColumnType("smallint");

                    b.HasKey("ID")
                        .HasAnnotation("SqlServer: identity", "(1,1)");

                    b.HasIndex("AssetID");

                    b.ToTable("AssetImages", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AssetID = 1,
                            ImageHeight = (short)150,
                            ImagePath = "C:\\User\\Samsung\\Images\\imageOne1.png",
                            ImageWidth = (short)150
                        },
                        new
                        {
                            ID = 2,
                            AssetID = 1,
                            ImageHeight = (short)150,
                            ImagePath = "C:\\User\\Samsung\\Images\\imageOne2.png",
                            ImageWidth = (short)150
                        },
                        new
                        {
                            ID = 3,
                            AssetID = 2,
                            ImageHeight = (short)150,
                            ImagePath = "C:\\User\\Samsung\\Images\\imageTwo1.png",
                            ImageWidth = (short)150
                        },
                        new
                        {
                            ID = 4,
                            AssetID = 2,
                            ImageHeight = (short)150,
                            ImagePath = "C:\\User\\Samsung\\Images\\imageTwo2.png",
                            ImageWidth = (short)150
                        },
                        new
                        {
                            ID = 5,
                            AssetID = 3,
                            ImageHeight = (short)150,
                            ImagePath = "C:\\User\\Samsung\\Images\\imageThree1.png",
                            ImageWidth = (short)150
                        },
                        new
                        {
                            ID = 6,
                            AssetID = 3,
                            ImageHeight = (short)150,
                            ImagePath = "C:\\User\\Samsung\\Images\\imageThree2.png",
                            ImageWidth = (short)150
                        });
                });

            modelBuilder.Entity("computrized_maintenance_Data_Access.Entites.AssetsManagment.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Category_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CategoryName");

                    b.HasKey("ID");

                    b.ToTable("AssetCategories", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Category_Name = "Production Equipment"
                        },
                        new
                        {
                            ID = 2,
                            Category_Name = "Facility Infrastructure"
                        },
                        new
                        {
                            ID = 3,
                            Category_Name = "Transportation"
                        },
                        new
                        {
                            ID = 4,
                            Category_Name = "IT Infrastructure"
                        },
                        new
                        {
                            ID = 5,
                            Category_Name = "Safety Equipment"
                        },
                        new
                        {
                            ID = 6,
                            Category_Name = "Tools"
                        },
                        new
                        {
                            ID = 7,
                            Category_Name = "Mechanical"
                        },
                        new
                        {
                            ID = 8,
                            Category_Name = "Electrical"
                        },
                        new
                        {
                            ID = 9,
                            Category_Name = "Electronic"
                        },
                        new
                        {
                            ID = 10,
                            Category_Name = "Hydraulic"
                        },
                        new
                        {
                            ID = 11,
                            Category_Name = "Pneumatic"
                        },
                        new
                        {
                            ID = 12,
                            Category_Name = "Process Equipment"
                        },
                        new
                        {
                            ID = 13,
                            Category_Name = "Support Equipment"
                        },
                        new
                        {
                            ID = 14,
                            Category_Name = "Standby Equipment"
                        },
                        new
                        {
                            ID = 15,
                            Category_Name = "Fire Protection"
                        },
                        new
                        {
                            ID = 16,
                            Category_Name = "Office Equipment"
                        },
                        new
                        {
                            ID = 17,
                            Category_Name = "Medical Equipment"
                        },
                        new
                        {
                            ID = 18,
                            Category_Name = "Laboratory Equipment"
                        },
                        new
                        {
                            ID = 19,
                            Category_Name = "Construction Equipment"
                        });
                });

            modelBuilder.Entity("computrized_maintenance_Data_Access.Entites.AssetsManagment.Location", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID")
                        .HasAnnotation("SqlServer: identity", "(1,1)");

                    b.ToTable("Locations", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            LocationName = "Main Warehouse"
                        },
                        new
                        {
                            ID = 2,
                            LocationName = "Secondary Storage"
                        },
                        new
                        {
                            ID = 3,
                            LocationName = "Outdoor Yard"
                        });
                });

            modelBuilder.Entity("computrized_maintenance_Data_Access.Entites.AssetsManagment.SubCategory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Sub_Category_Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("ID")
                        .HasAnnotation("SqlServer = Identity", "(1,1)");

                    b.HasIndex("CategoryID");

                    b.ToTable("SubCategories", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CategoryID = 1,
                            Sub_Category_Name = "CNC Machines"
                        },
                        new
                        {
                            ID = 2,
                            CategoryID = 1,
                            Sub_Category_Name = "Assembly Lines"
                        },
                        new
                        {
                            ID = 3,
                            CategoryID = 2,
                            Sub_Category_Name = "HVAC Systems"
                        },
                        new
                        {
                            ID = 4,
                            CategoryID = 2,
                            Sub_Category_Name = "Electrical Systems"
                        });
                });

            modelBuilder.Entity("computrized_maintenance_Data_Access.Entites.DownTimeTracking.DownTimeEvent", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ActionTaken")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnOrder(7);

                    b.Property<int>("AssetID")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(8);

                    b.Property<string>("DownTimeType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnOrder(5);

                    b.Property<DateTime?>("EndDownTimeEvent")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(4);

                    b.Property<int>("PerformedByID")
                        .HasColumnType("int")
                        .HasColumnOrder(9);

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnOrder(6);

                    b.Property<DateTime>("StartDownTimeEvent")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(3);

                    b.Property<int?>("WO_ID")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.HasKey("ID")
                        .HasAnnotation("Sql server identity", "1,1");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("ID"));

                    b.HasIndex("AssetID");

                    b.HasIndex("WO_ID");

                    b.ToTable("DownTimeEvents", "report");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            ActionTaken = "Replaced bearing and added lubrication",
                            AssetID = 1,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DownTimeType = "Unplanned",
                            EndDownTimeEvent = new DateTime(2025, 10, 10, 10, 45, 0, 0, DateTimeKind.Unspecified),
                            PerformedByID = 1,
                            Reason = "Motor overheating due to lack of lubrication",
                            StartDownTimeEvent = new DateTime(2025, 10, 10, 8, 15, 0, 0, DateTimeKind.Unspecified),
                            WO_ID = 1
                        },
                        new
                        {
                            ID = 2,
                            ActionTaken = "Installed new firmware and tested functionality",
                            AssetID = 3,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DownTimeType = "Planned",
                            EndDownTimeEvent = new DateTime(2025, 10, 12, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            PerformedByID = 6,
                            Reason = "Scheduled control system upgrade",
                            StartDownTimeEvent = new DateTime(2025, 10, 12, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            WO_ID = 2
                        },
                        new
                        {
                            ID = 3,
                            ActionTaken = "Recalibrated sensor and updated firmware",
                            AssetID = 3,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DownTimeType = "Unplanned",
                            EndDownTimeEvent = new DateTime(2025, 10, 15, 9, 45, 0, 0, DateTimeKind.Unspecified),
                            PerformedByID = 6,
                            Reason = "Unexpected sensor calibration issue",
                            StartDownTimeEvent = new DateTime(2025, 10, 15, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("computrized_maintenance_Data_Access.Entites.InventoryManagement.InventoryItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("LocationID")
                        .HasColumnType("int");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<short>("Quintity")
                        .HasColumnType("smallint");

                    b.Property<short>("ReorderLevel")
                        .HasColumnType("smallint");

                    b.Property<decimal>("UnitCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID")
                        .HasAnnotation("Sql server Identity", "1,1");

                    b.HasIndex("LocationID");

                    b.ToTable("InventoryItems", "Inventory");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "Standard HVAC air filter, 20x25x2 inches.",
                            IsActive = true,
                            ItemName = "Air Filter",
                            LocationID = 1,
                            PartNumber = "AF-1001",
                            Quintity = (short)47,
                            ReorderLevel = (short)10,
                            UnitCost = 12.50m
                        },
                        new
                        {
                            ID = 2,
                            Description = "High-pressure hydraulic hose, 2-meter length.",
                            IsActive = true,
                            ItemName = "Hydraulic Hose",
                            LocationID = 2,
                            PartNumber = "HH-2045",
                            Quintity = (short)18,
                            ReorderLevel = (short)5,
                            UnitCost = 45.75m
                        },
                        new
                        {
                            ID = 3,
                            Description = "Synthetic lubricant oil, 5-liter container.",
                            IsActive = true,
                            ItemName = "Lubricant Oil",
                            LocationID = 1,
                            PartNumber = "LO-3020",
                            Quintity = (short)15,
                            ReorderLevel = (short)5,
                            UnitCost = 38.90m
                        },
                        new
                        {
                            ID = 4,
                            Description = "Industrial safety valve, 2-inch diameter.",
                            IsActive = false,
                            ItemName = "Safety Valve",
                            LocationID = 3,
                            PartNumber = "SV-1550",
                            Quintity = (short)0,
                            ReorderLevel = (short)3,
                            UnitCost = 120.00m
                        },
                        new
                        {
                            ID = 5,
                            Description = "Replacement motor for conveyor belt system.",
                            IsActive = true,
                            ItemName = "Conveyor Belt Motor",
                            LocationID = 2,
                            PartNumber = "CBM-450",
                            Quintity = (short)1,
                            ReorderLevel = (short)1,
                            UnitCost = 350.00m
                        },
                        new
                        {
                            ID = 6,
                            Description = "Digital pressure sensor, 0–10 bar range.",
                            IsActive = false,
                            ItemName = "Pressure Sensor",
                            LocationID = 3,
                            PartNumber = "PS-8812",
                            Quintity = (short)0,
                            ReorderLevel = (short)4,
                            UnitCost = 78.40m
                        });
                });

            modelBuilder.Entity("computrized_maintenance_Data_Access.Entites.PM_SchedulingManagement.PMSchedule", b =>
                {
                    b.Property<int>("ScheduleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastCompletionDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("NextDueDate")
                        .HasColumnType("datetime");

                    b.Property<int>("PmID")
                        .HasColumnType("int")
                        .HasColumnName("PM_Id");

                    b.HasKey("ScheduleID")
                        .HasName("PK_Schedules")
                        .HasAnnotation("SqlServer Identity", "1,1");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("ScheduleID"));

                    b.HasIndex("NextDueDate")
                        .HasDatabaseName("IX_Schedules_NextDueDate");

                    b.HasIndex("PmID")
                        .HasDatabaseName("IX_Schedules_PM_Id");

                    b.ToTable("Schedules", "maintain");

                    b.HasData(
                        new
                        {
                            ScheduleID = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            LastCompletionDate = new DateTime(2026, 2, 22, 22, 30, 10, 0, DateTimeKind.Unspecified),
                            NextDueDate = new DateTime(2026, 3, 1, 11, 20, 0, 0, DateTimeKind.Unspecified),
                            PmID = 1
                        },
                        new
                        {
                            ScheduleID = 2,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            NextDueDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PmID = 1
                        },
                        new
                        {
                            ScheduleID = 3,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            LastCompletionDate = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NextDueDate = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PmID = 2
                        },
                        new
                        {
                            ScheduleID = 4,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            IsDeleted = false,
                            NextDueDate = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PmID = 2
                        });
                });

            modelBuilder.Entity("computrized_maintenance_Data_Access.Entites.PM_SchedulingManagement.PreventiveMaintenance", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AssetID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("TaskDescription")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("ID")
                        .HasAnnotation("Sql server Identity", "1,1");

                    b.HasIndex("AssetID");

                    b.ToTable("PreventiveMaintenances", "maintain");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AssetID = 3,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Frequency = "Quarterly",
                            IsDeleted = false,
                            TaskDescription = "Replace air filter in HVAC unit every 3 months."
                        },
                        new
                        {
                            ID = 2,
                            AssetID = 2,
                            CreatedDate = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Frequency = "SemiAnnual",
                            IsDeleted = false,
                            TaskDescription = "Inspect safety valves on boiler system every 6 months."
                        });
                });

            modelBuilder.Entity("computrized_maintenance_Data_Access.Entites.ReportsAndAnalysis.Report", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AssetID")
                        .HasColumnType("int");

                    b.Property<decimal>("Availability")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("EndPeriod")
                        .HasColumnType("datetime");

                    b.Property<float>("Interval_Running_machine")
                        .HasColumnType("real");

                    b.Property<decimal>("MDT")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Mean_DownTime");

                    b.Property<decimal>("MTBF")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Mean_Time_between_Failure");

                    b.Property<decimal>("MTTR")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Mean_Time_TO_Repair");

                    b.Property<DateTime>("StartPeriod")
                        .HasColumnType("datetime");

                    b.HasKey("ID")
                        .HasAnnotation("Sql server identity", "1,1");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("ID"));

                    b.HasIndex("AssetID");

                    b.ToTable("Reports");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AssetID = 1,
                            Availability = 0.92m,
                            CreateAt = new DateTime(2021, 8, 12, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            EndPeriod = new DateTime(2025, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Interval_Running_machine = 300.5f,
                            MDT = 2.5m,
                            MTBF = 12.4m,
                            MTTR = 1.7m,
                            StartPeriod = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 2,
                            AssetID = 2,
                            Availability = 0.88m,
                            CreateAt = new DateTime(2021, 8, 12, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            EndPeriod = new DateTime(2025, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Interval_Running_machine = 250f,
                            MDT = 3.4m,
                            MTBF = 15.3m,
                            MTTR = 2.1m,
                            StartPeriod = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("computrized_maintenance_Data_Access.Entites.WorkOrderManagement.InventoryTransaction", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("InventoryItemID")
                        .HasColumnType("int");

                    b.Property<short>("Quntity")
                        .HasColumnType("smallint");

                    b.Property<string>("Reference")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID")
                        .HasAnnotation("Sql Server Identity", "1,1");

                    b.HasIndex("InventoryItemID");

                    b.ToTable("InventoryTransactions", "Inventory");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            InventoryItemID = 1,
                            Quntity = (short)100,
                            TransactionDate = new DateTime(2025, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = "In"
                        },
                        new
                        {
                            ID = 2,
                            InventoryItemID = 1,
                            Quntity = (short)20,
                            Reference = "WO-0001",
                            TransactionDate = new DateTime(2025, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = "Out"
                        },
                        new
                        {
                            ID = 3,
                            InventoryItemID = 2,
                            Quntity = (short)10,
                            TransactionDate = new DateTime(2025, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = "In"
                        },
                        new
                        {
                            ID = 4,
                            InventoryItemID = 2,
                            Quntity = (short)3,
                            TransactionDate = new DateTime(2025, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = "Out"
                        },
                        new
                        {
                            ID = 5,
                            InventoryItemID = 3,
                            Quntity = (short)2,
                            TransactionDate = new DateTime(2025, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = "Out"
                        });
                });

            modelBuilder.Entity("computrized_maintenance_Data_Access.Entites.WorkOrderManagement.WorkOrder", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AssetID")
                        .HasColumnType("int");

                    b.Property<int>("AssignedToID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompeletedDate")
                        .HasColumnType("datetime");

                    b.Property<int>("CreatedByID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PreventiveMaintenanceID")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkOrderNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("ID")
                        .HasAnnotation("Sql server Identity", "1,1");

                    b.HasIndex("AssetID");

                    b.HasIndex("PreventiveMaintenanceID");

                    b.ToTable("WorkOrders", "maintain");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AssetID = 3,
                            AssignedToID = 1,
                            CreatedByID = 22,
                            CreatedDate = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Replace air filter in HVAC unit.",
                            DueDate = new DateTime(2025, 10, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "Check stock for spare filters before starting.",
                            PreventiveMaintenanceID = 1,
                            StartDate = new DateTime(2025, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Open",
                            Type = "corrective",
                            WorkOrderNumber = "WO-0001"
                        },
                        new
                        {
                            ID = 2,
                            AssetID = 2,
                            AssignedToID = 1,
                            CompeletedDate = new DateTime(2025, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedByID = 5,
                            CreatedDate = new DateTime(2025, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Inspect safety valves on boiler system.",
                            DueDate = new DateTime(2025, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "All valves passed inspection.",
                            PreventiveMaintenanceID = 2,
                            StartDate = new DateTime(2025, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed",
                            Type = "corrective",
                            WorkOrderNumber = "WO-0002"
                        });
                });

            modelBuilder.Entity("computrized_maintenance_Data_Access.Entites.WorkOrderManagement.WorkOrderHistory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PerformedActionByID")
                        .HasColumnType("int");

                    b.Property<int>("WO_ID")
                        .HasColumnType("int");

                    b.HasKey("ID")
                        .HasAnnotation("Sql server Identity", "1,1");

                    b.HasIndex("WO_ID");

                    b.ToTable("WorkOrderHisties", "maintain");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Action = "Created",
                            ActionDate = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PerformedActionByID = 22,
                            WO_ID = 1
                        },
                        new
                        {
                            ID = 2,
                            Action = "Assgined",
                            ActionDate = new DateTime(2025, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PerformedActionByID = 22,
                            WO_ID = 1
                        },
                        new
                        {
                            ID = 3,
                            Action = "Created",
                            ActionDate = new DateTime(2025, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PerformedActionByID = 5,
                            WO_ID = 2
                        },
                        new
                        {
                            ID = 4,
                            Action = "Completed",
                            ActionDate = new DateTime(2025, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PerformedActionByID = 1,
                            WO_ID = 2
                        });
                });

            modelBuilder.Entity("computrized_maintenance_Data_Access.Entites.WorkOrderManagement.WorkOrderPart", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("PartItemID")
                        .HasColumnType("int");

                    b.Property<short>("QuantityUsed")
                        .HasColumnType("smallint");

                    b.Property<int>("WO_ID")
                        .HasColumnType("int");

                    b.HasKey("ID")
                        .HasAnnotation("Sql server Identity", "1,1");

                    b.HasIndex("PartItemID");

                    b.HasIndex("WO_ID");

                    b.ToTable("WorkOrderParts", "maintain");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            PartItemID = 2,
                            QuantityUsed = (short)2,
                            WO_ID = 1
                        },
                        new
                        {
                            ID = 2,
                            PartItemID = 5,
                            QuantityUsed = (short)1,
                            WO_ID = 1
                        },
                        new
                        {
                            ID = 3,
                            PartItemID = 1,
                            QuantityUsed = (short)3,
                            WO_ID = 2
                        });
                });

            modelBuilder.Entity("computrized_maintenance_Data_Access.Entites.AssetsManagment.Asset", b =>
                {
                    b.HasOne("computrized_maintenance_Data_Access.Entites.AssetsManagment.Category", "Category")
                        .WithOne("Asset")
                        .HasForeignKey("computrized_maintenance_Data_Access.Entites.AssetsManagment.Asset", "AssetCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("computrized_maintenance_Data_Access.Entites.AssetsManagment.Location", "Location")
                        .WithOne("Asset")
                        .HasForeignKey("computrized_maintenance_Data_Access.Entites.AssetsManagment.Asset", "AssetLocationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("computrized_maintenance_Data_Access.Entites.AssetsManagment.AssetImage", b =>
                {
                    b.HasOne("computrized_maintenance_Data_Access.Entites.AssetsManagment.Asset", "Asset")
                        .WithMany("AssetImages")
                        .HasForeignKey("AssetID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("computrized_maintenance_Data_Access.Entites.AssetsManagment.SubCategory", b =>
                {
                    b.HasOne("computrized_maintenance_Data_Access.Entites.AssetsManagment.Category", "Category")
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("computrized_maintenance_Data_Access.Entites.DownTimeTracking.DownTimeEvent", b =>
                {
                    b.HasOne("computrized_maintenance_Data_Access.Entites.AssetsManagment.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("computrized_maintenance_Data_Access.Entites.WorkOrderManagement.WorkOrder", "WorkOrder")
                        .WithMany()
                        .HasForeignKey("WO_ID");

                    b.Navigation("Asset");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("computrized_maintenance_Data_Access.Entites.InventoryManagement.InventoryItem", b =>
                {
                    b.HasOne("computrized_maintenance_Data_Access.Entites.AssetsManagment.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("computrized_maintenance_Data_Access.Entites.PM_SchedulingManagement.PMSchedule", b =>
                {
                    b.HasOne("computrized_maintenance_Data_Access.Entites.PM_SchedulingManagement.PreventiveMaintenance", "PreventiveMaintenance")
                        .WithMany("PMSchedules")
                        .HasForeignKey("PmID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Schedules_PreventiveMaintenance");

                    b.Navigation("PreventiveMaintenance");
                });

            modelBuilder.Entity("computrized_maintenance_Data_Access.Entites.PM_SchedulingManagement.PreventiveMaintenance", b =>
                {
                    b.HasOne("computrized_maintenance_Data_Access.Entites.AssetsManagment.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("computrized_maintenance_Data_Access.Entites.ReportsAndAnalysis.Report", b =>
                {
                    b.HasOne("computrized_maintenance_Data_Access.Entites.AssetsManagment.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("computrized_maintenance_Data_Access.Entites.WorkOrderManagement.InventoryTransaction", b =>
                {
                    b.HasOne("computrized_maintenance_Data_Access.Entites.InventoryManagement.InventoryItem", "InventoryItem")
                        .WithMany("Transactions")
                        .HasForeignKey("InventoryItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryItem");
                });

            modelBuilder.Entity("computrized_maintenance_Data_Access.Entites.WorkOrderManagement.WorkOrder", b =>
                {
                    b.HasOne("computrized_maintenance_Data_Access.Entites.AssetsManagment.Asset", "Asset")
                        .WithMany("WorkOrders")
                        .HasForeignKey("AssetID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("computrized_maintenance_Data_Access.Entites.PM_SchedulingManagement.PreventiveMaintenance", "PreventiveMaintenance")
                        .WithMany("WorkOrders")
                        .HasForeignKey("PreventiveMaintenanceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("PreventiveMaintenance");
                });

            modelBuilder.Entity("computrized_maintenance_Data_Access.Entites.WorkOrderManagement.WorkOrderHistory", b =>
                {
                    b.HasOne("computrized_maintenance_Data_Access.Entites.WorkOrderManagement.WorkOrder", "WorkOrder")
                        .WithMany("Histories")
                        .HasForeignKey("WO_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("computrized_maintenance_Data_Access.Entites.WorkOrderManagement.WorkOrderPart", b =>
                {
                    b.HasOne("computrized_maintenance_Data_Access.Entites.InventoryManagement.InventoryItem", "InventoryItem")
                        .WithMany("WorkOrderParts")
                        .HasForeignKey("PartItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("computrized_maintenance_Data_Access.Entites.WorkOrderManagement.WorkOrder", "WorkOrder")
                        .WithMany("UsedParts")
                        .HasForeignKey("WO_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryItem");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("computrized_maintenance_Data_Access.Entites.AssetsManagment.Asset", b =>
                {
                    b.Navigation("AssetImages");

                    b.Navigation("WorkOrders");
                });

            modelBuilder.Entity("computrized_maintenance_Data_Access.Entites.AssetsManagment.Category", b =>
                {
                    b.Navigation("Asset")
                        .IsRequired();

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("computrized_maintenance_Data_Access.Entites.AssetsManagment.Location", b =>
                {
                    b.Navigation("Asset")
                        .IsRequired();
                });

            modelBuilder.Entity("computrized_maintenance_Data_Access.Entites.InventoryManagement.InventoryItem", b =>
                {
                    b.Navigation("Transactions");

                    b.Navigation("WorkOrderParts");
                });

            modelBuilder.Entity("computrized_maintenance_Data_Access.Entites.PM_SchedulingManagement.PreventiveMaintenance", b =>
                {
                    b.Navigation("PMSchedules");

                    b.Navigation("WorkOrders");
                });

            modelBuilder.Entity("computrized_maintenance_Data_Access.Entites.WorkOrderManagement.WorkOrder", b =>
                {
                    b.Navigation("Histories");

                    b.Navigation("UsedParts");
                });
#pragma warning restore 612, 618
        }
    }
}
